import Head from "next/head"
import { MainView } from "@views/MainView/MainView"
import Layout from "@components/Layout/Layout"
import { ReactElement } from "react"

function Home() {
	return (
		<>
			<Head>
				<title>Margo Lesniak | Front-end</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<MainView />
		</>
	)
}

Home.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>
}

export default Home
