import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import { MainView } from '@views/MainView/MainView'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>cadF</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap"
            rel="stylesheet"
          />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainView />
      
    </>
  )
}
