import { ProjectsView } from "@views/ProjectsView/ProjectsView"
import Head from "next/head"
import Layout from "@components/Layout/Layout"
import { ReactElement } from "react"

export default function ProjectsPage() {
	return (
		<>
			<Head>
				<title>Margo Lesniak | Projects</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<ProjectsView />
		</>
	)
}

ProjectsPage.getLayout = function getLayout(page: ReactElement) {
	return <Layout>{page}</Layout>
}
